name = "TTT Creative"
author = "The Tiny Taters"
version = "2.2.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f53ee8c9778c2fc05cc8b6b369026abcf9910d4aaafeac62affdbbaab957669b"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
