name = "TTT Creative"
author = "The Tiny Taters"
version = "2.2.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83287e697fa9f6e8902bca413f1915c0e26065bee0c83e8c34efd420fe6675a6"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
