name = "TTT Creative"
author = "The Tiny Taters"
version = "2.2.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b7ecf201f9520a694d506e7cb0092364520140dfef877e4c8ee90a8df5c5e51"

[versions]
fabric = "0.11.2"
minecraft = "1.16.5"
