name = "Alloy Forgery"
filename = "wraith-alloy_forgery-1.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3305/755/wraith-alloy_forgery-1.2.0.jar"
hash-format = "murmur2"
hash = "2354998999"

[update]
[update.curseforge]
file-id = 3305755
project-id = 438718
release-channel = "beta"
