name = "Bits And Chisels"
filename = "bitsandchisels-2.3.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3316/838/bitsandchisels-2.3.0.jar"
hash-format = "murmur2"
hash = "1212363365"

[update]
[update.curseforge]
file-id = 3316838
project-id = 420709
release-channel = "beta"
