name = "Consistency+"
filename = "consistency_plus-0.3.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/nDHcEOt3/versions/0.3/consistency_plus-0.3.0.jar"
hash-format = "sha512"
hash = "e14d2da11a12cb68e65d146afc73d9b054632bf6f4392a0326fa1db7119b319ad244c1f93b4a31319dd70b2f6d4a62931e5c10565da0bb7a276e65a98259296c"

[update]
[update.modrinth]
mod-id = "nDHcEOt3"
version = "MTMIcme6"
