name = "FabricTPA"
filename = "FabricTPA-2.0.1.jar"
side = "server"

[download]
url = "https://edge.forgecdn.net/files/3261/976/FabricTPA-2.0.1.jar"
hash-format = "murmur2"
hash = "4148827266"

[update]
[update.curseforge]
file-id = 3261976
project-id = 423295
release-channel = "beta"
