name = "HealthCare"
filename = "healthcare-1.0.2.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/NNqujQWr/versions/1.0.2/healthcare-1.0.2.jar"
hash-format = "sha512"
hash = "c64f51c425db0db3dcf30f31e51b07ca8096864eef1aec54d2b06a9e544a83e1f26d4ba6b840ca643613c456ed690b905b6a8a84fd618c4f3dceaad89676f5be"

[update]
[update.modrinth]
mod-id = "NNqujQWr"
version = "ps9CnBg9"
