name = "HealthCare"
filename = "healthcare-1.0.3.jar"
side = "server"

[download]
url = "https://cdn.modrinth.com/data/NNqujQWr/versions/1.0.3/healthcare-1.0.3.jar"
hash-format = "sha512"
hash = "518fd7a4a86e7c35db6001a8410adf13d4ba341b09d917331fcb5a7f829b6b886fef176e2d407cffb70d3ef0146ea09cce2ba7a91034b95b40fa984b9c9def26"

[update]
[update.modrinth]
mod-id = "NNqujQWr"
version = "5Opzs2mZ"
