name = "Immigistics"
filename = "immigistics-0.1.3.jar"
side = "both"

[download]
url = "https://immibis.com/mcmoddl/files/immigistics-0.1.3.jar"
hash-format = "sha256"
hash = "5820852ED34F7DF5AFDCF1A911E833471A8F3285283B8F332E8E94C9B2726DCF"
