name = "Taterzens"
filename = "taterzens-1.0.4-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/vE972Kux/versions/1.0.4/taterzens-1.0.4-fabric.jar"
hash-format = "sha512"
hash = "dd635bbc52fda23651a8a1c99cdb2de6373d2f053981d3bef6b993aa2c8c128df4b1bc0c7b63debda64fc1d079dde585b6a4212b75d79d7f0069eacf988f5881"

[update]
[update.modrinth]
mod-id = "vE972Kux"
version = "PfRv1mLH"
