name = "UnderFabric"
filename = "underfabric-1.2.3.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/UXm0RHnT/versions/1.2.3/underfabric-1.2.3.jar"
hash-format = "sha512"
hash = "f0dd52517fb2dd22d3bc677af392a7490941dbaaf30c0f07b34cc4cd6b09579747a183abc4df874edcd16607d1ae0b6fcd18d8a5341cf3a4cf70a2e01d3229e7"

[update]
[update.modrinth]
mod-id = "UXm0RHnT"
version = "W36MkxmB"
